Incident/Models/ErrorViewModel.cs
using System;

namespace Incident.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Incident/Models/Incident.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Incident.Models
{
    public class Incident
    {
        public int Id { get; set; }
        public string Type { get; set; } //change this to an enum
        public DateTime DateOfIncident { get; set; }
        public TimeSpan TimeOfIncident { get; set; }
        public string Description { get; set; }
        public string RaisedUser { get; set; }
    }
}

Incident/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Incident.Models;

namespace Incident.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View("Index");
        }

        public IActionResult Error()
        {
            return View("Error");
        }
    }
}

Incident/Controllers/IncidentController.cs
using System.Linq;
using Incident.Data;
using Microsoft.AspNetCore.Mvc;

namespace Incident.Controllers
{
    public class ItemController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ItemController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var model = _context.Incidents.ToList();
            return View("Index", model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View("Create");
        }

        [HttpPost]
        public IActionResult Create(Models.Incident item)
        {
            _context.Incidents.Add(item);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        
        public IActionResult Delete(int id)
        {
            var incident = _context.Incidents.FirstOrDefault(e => e.Id == id);
            _context.Incidents.Remove(incident);
            _context.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

Incident/Views/Home/Index.cshtml
<h1>Welcome!</h1>

<a asp-action="Index" asp-controller="Item">View Incidents</a>

Incident/Views/Item/Create.cshtml
@model Incident.Models.Incident

<h3>Report Incident</h3>

<form asp-action="create">
    <input asp-for="DateOfIncident" />
    <span asp-validation-for="DateOfIncident"></span>
    
    <input asp-for="Description" />
    <span asp-validation-for="Description"></span>
    <button type="submit">Raise Incident</button>

</form>

Incident/Views/Item/Index.cshtml
@model List<Incident.Models.Incident>

<h1>Incidents</h1>

<a asp-action="create">Add Incident</a>

<ul>
    @foreach (var incident in Model)
    {
        <li>@incident.Description <a asp-action="delete" asp-route-id="@incident.Id">delete</a></li>
    }
    
</ul>

Incident/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Incident</title>

    <!-- Handles styling the page to be more aesthetically pleasing -->
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css" />
</head>

<body>
<!-- Where view content will be rendered -->
<div class="col-sm-12">
    @RenderBody()
</div>

<!-- Needed for client side validation, dialogs, etc -->
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.0.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>